<div>
    <x-site.project-detail
        :project="$project"
        :readmeHtml="$readmeHtml"
        :versions="$versions"
        :versionGroups="$versionGroups"
        :activeVersion="$activeVersion"
        :ref="$ref"
    />
</div>
